app:
  host: "0.0.0.0"
  port: '5235'
  debug: 'True'

storage:
  max_snapshots_per_volume: '3'
  max_total_size_gb: '50'
  snapshot_interval_minutes: '2'

monitoring:
  monitoring_interval_minutes: '3'

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: '587'
  sender_email: "simonaTest23@gmail.com"
  app_password: "rqsj obct otjo vcsh"
  recipient_email: "simonaettari@libero.it"

